apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-html-pv-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/nginx-html-2"