apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: kubernetes.io/basic-auth
data:
  username: V2lsbGlhbg==
  password: V2lsbGlhbg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: password
          volumeMounts:
          - name: credentials
            mountPath: "/tmp"
            readOnly: true
      volumes:
        - name: credentials
          secret:
            secretName: credentials

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOamb5ZaBsXPIbEQ64/q/k1rr4H2ofmGxSh/V7V32QXM operador
